#!/bin/bash

chown www-data:www-data /var/www -R

while ! (mysqladmin ping --host=database --user=root --password=MYSQL_ROOT_PASSWORD > /dev/null 2>&1)
do
   sleep 3
   echo "Waiting till MySQL service is available..."
done

source /usr/local/bin/databases

if [[ $1 = "tests" ]]; then
  source /usr/local/bin/single_tests
  source /usr/local/bin/multi_tests
else
  source /usr/local/bin/single
  source /usr/local/bin/single_tests
  source /usr/local/bin/multi
  source /usr/local/bin/multi_tests
fi

cd /var/www || exit 1
