#!/bin/bash

chown www-data:www-data /var/www -R

source /usr/local/bin/databases

if (( WAIT_SERVICES_IN_SECONDS > 0 )); then
  echo "Waiting for services to kickin for ${WAIT_SERVICES_IN_SECONDS} seconds"
  sleep "${WAIT_SERVICES_IN_SECONDS}"
fi

if [[ $1 = "single" ]]; then
  source /usr/local/bin/single
elif [[ $1 = "multi" ]]; then
  source /usr/local/bin/multi
else
  source /usr/local/bin/single
  source /usr/local/bin/multi
fi

cd /var/www || exit 1
