#!/bin/bash
PATH_MULTI=/var/www/multi_tests/

chown www-data:www-data /var/www/multi_tests -R

echo "Installing WordPress Multi in ${PATH_MULTI}"
cd $PATH_MULTI || exit 1

if [ ! -f $PATH_MULTI"wp-config.php" ]; then
  echo "Downloading WordPress"
  su www-data -c "wp core download"
fi

if [ -f $PATH_MULTI"wp-config.php" ]; then
  echo "Backing up wp-config.php file..."
  mv $PATH_MULTI"wp-config.php" $PATH_MULTI"wp-config.php.bak"
fi

RES=$(su www-data -c "wp --path=$PATH_MULTI core config --dbname=$MYSQL_DATABASE_MULTI_TESTS --dbuser=$MYSQL_USER --dbpass=$MYSQL_PASSWORD --dbhost=database --dbprefix=wp_")
if [[ $RES != *"Success"* ]]; then
  echo "Failed to create config..."
  if [ -f $PATH_MULTI"wp-config.php.bak" ]; then
    echo "Restoring wp-config.php backup..."
    mv $PATH_MULTI"wp-config.php.bak" $PATH_MULTI"wp-config.php"
  fi
  exit 1
fi

if [ -f $PATH_MULTI"wp-config.php.bak" ]; then
  echo -n "Removing wp-config.php backup..."
  rm -f $PATH_MULTI"wp-config.php.bak"
fi

RES=$(su www-data -c "wp --path=$PATH_MULTI db query 'SHOW DATABASES LIKE \"$MYSQL_DATABASE_MULTI_TESTS\";'" )
if [[ ! ${#RES} -gt 0 ]]; then
  echo "Database not found, creating database..."
  su www-data -c "wp --path=$PATH_MULTI db create"
  exit 1
fi

echo "Installing WP"
su www-data -c "wp --path=$PATH_MULTI core install --url=\"https://${HOST_MULTI_TESTS}\" --title=\"WP Staging Multi\" --admin_user=\"${WP_ADMIN_USERNAME}\" --admin_password=\"${WP_ADMIN_PASSWORD}\" --admin_email=\"${WP_ADMIN_EMAIL}\""

echo "Updating wp-config.php..."
su www-data -c "wp config set WP_DEBUG true"
su www-data -c "wp config set WP_DISPLAY true"

chmod 644 "${PATH_MULTI}wp-config.php"

echo "Disabling Unneccessary Plugins"
su www-data -c "wp --path=$PATH_MULTI plugin deactivate hello"
su www-data -c "wp --path=$PATH_MULTI plugin deactivate akismet"
su www-data -c "wp --path=$PATH_MULTI plugin delete hello"
su www-data -c "wp --path=$PATH_MULTI plugin delete akismet"

echo "Enabling WP-Staging PRO Plugin: "
su www-data -c "wp --path=$PATH_MULTI plugin activate wp-staging"

UPLOADS_PATH=$PATH_MULTI"wp-content/uploads"
if [ ! -d $UPLOADS_PATH ]; then
  echo "Enabling uploads..."
  mkdir $UPLOADS_PATH
  chmod 775 $UPLOADS_PATH
fi

echo "Converting to Multi Site"
su www-data -c "wp --path=$PATH_MULTI core multisite-convert"
