#!/bin/bash
PATH_SINGLE=/var/www/single/

chown www-data:www-data /var/www/single -R

echo "Installing WordPress in ${PATH_SINGLE}"
cd $PATH_SINGLE || exit 1

if [ ! -f $PATH_SINGLE"wp-config.php" ]; then
  echo "Downloading WordPress"
  su www-data -c "wp core download"
fi

if [ -f $PATH_SINGLE"wp-config.php" ]; then
  echo "Backing up wp-config.php file..."
  mv $PATH_SINGLE"wp-config.php" $PATH_SINGLE"wp-config.php.bak"
fi

RES=$(su www-data -c "wp --path=$PATH_SINGLE core config --dbname=$MYSQL_DATABASE_SINGLE --dbuser=$MYSQL_USER --dbpass=$MYSQL_PASSWORD --dbhost=database")
if [[ $RES != *"Success"* ]]; then
  echo "Failed to create config..."
  if [ -f $PATH_SINGLE"wp-config.php.bak" ]; then
    echo "Restoring wp-config.php backup..."
    mv $PATH_SINGLE"wp-config.php.bak" $PATH_SINGLE"wp-config.php"
  fi
  exit 1
fi

if [ -f $PATH_SINGLE"wp-config.php.bak" ]; then
  echo -n "Removing wp-config.php backup..."
  rm -f $PATH_SINGLE"wp-config.php.bak"
fi

RES=$(su www-data -c "wp --path=$PATH_SINGLE db query 'SHOW DATABASES LIKE \"$MYSQL_DATABASE_SINGLE\";'" )
if [[ ! ${#RES} -gt 0 ]]; then
  echo "Database not found, creating database..."
  su www-data -c "wp --path=$PATH_SINGLE db create"
  exit 1
fi

rm -f $PATH_SINGLE"wp-config.php"
echo "Creating config..."
su www-data -c "wp --path=$PATH_SINGLE core config --dbname=$MYSQL_DATABASE_SINGLE --dbuser=$MYSQL_USER --dbpass=$MYSQL_PASSWORD --dbhost=database <<PHP
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', true);
define('WP_MEMORY_LIMIT', '512M');
PHP"


chmod 644 "${PATH_SINGLE}wp-config.php"

echo "Installing WP"
su www-data -c "wp --path=$PATH_SINGLE core install --url=\"https://${HOST_SINGLE}\" --title=\"WP Staging\" --admin_user=\"${WP_ADMIN_USERNAME}\" --admin_password=\"${WP_ADMIN_PASSWORD}\" --admin_email=\"${WP_ADMIN_EMAIL}\""

echo "Disabling Unneccessary Plugins"
su www-data -c "wp --path=$PATH_SINGLE plugin deactivate hello"
su www-data -c "wp --path=$PATH_SINGLE plugin deactivate akismet"
su www-data -c "wp --path=$PATH_SINGLE plugin delete hello"
su www-data -c "wp --path=$PATH_SINGLE plugin delete akismet"

echo "Enabling WP-Staging Plugin: "
su www-data -c "wp --path=$PATH_SINGLE plugin activate wp-staging"
su www-data -c "wp --path=$PATH_SINGLE db query 'INSERT INTO wp_options (option_name, option_value) VALUES(\"wpstg_license_key\", \"${LICENSE_KEY}\");'"

echo "Installing Extra Plugins"
su www-data -c "wp plugin install query-monitor --activate"

UPLOADS_PATH=$PATH_SINGLE"wp-content/uploads"
if [ ! -d $UPLOADS_PATH ]; then
  echo "Enabling uploads..."
  mkdir $UPLOADS_PATH
  chmod 775 $UPLOADS_PATH
fi
