#!/bin/bash
PATH_TEST=/var/www/test/

mkdir -p /$PATH_TEST

chown www-data:www-data /var/www/test -R

echo "Downloading WordPress in ${PATH_TEST}"
cd $PATH_TEST || exit 1

su www-data -c "wp core download"

UPLOADS_PATH=$PATH_TEST"wp-content/uploads"
if [ ! -d $UPLOADS_PATH ]; then
  echo "Enabling uploads..."
  mkdir $UPLOADS_PATH
  chmod 775 $UPLOADS_PATH
fi