version: '3.7'

volumes:
  database:
    driver: local

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}

services:
  database:
    image: mariadb:10.4
    command:
      --max_allowed_packet=1073741824
      --innodb_log_file_size=1073741824
    environment:
      - MYSQL_DATABASE_SINGLE=${MYSQL_DATABASE_SINGLE}
      - MYSQL_DATABASE_MULTI=${MYSQL_DATABASE_MULTI}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - database:/var/lib/mysql
    ports:
      - ${DOCKER_GATEWAY_IP}:3306:3306
  php-fpm:
    image: wpstaging/php7.3-fpm:ci
    env_file: .env
    depends_on:
      - database
    volumes:
      - ./var/www:/var/www
      - ./src/.:/var/www/single/wp-content/plugins/wp-staging-pro
      - ./src/.:/var/www/single_tests/wp-content/plugins/wp-staging-pro
      - ./src/.:/var/www/multi/wp-content/plugins/wp-staging-pro
      - ./src/.:/var/www/multi_tests/wp-content/plugins/wp-staging-pro
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php/uploads.ini:/usr/local/etc/php/php.ini
      - ./docker/install/install:/usr/local/bin/install:ro
      - ./docker/install/databases:/usr/local/bin/databases:ro
      - ./docker/install/single:/usr/local/bin/multi:ro
      - ./docker/install/multi:/usr/local/bin/single:ro
      - ./docker/install/single_tests:/usr/local/bin/single_tests:ro
      - ./docker/install/multi_tests:/usr/local/bin/multi_tests:ro
      - ./codeception.dist.yml:/var/www/tests/codeception.dist.yml:ro
      - ./phpstan.dist.neon:/var/www/tests/phpstan.dist.neon:ro
      - ./phpcs.xml.dist:/var/www/tests/phpcs.xml.dist:ro
      - ./.env:/var/www/tests/.env:ro
      - ./vendor:/var/www/tests/vendor
      - ./tests:/var/www/tests/tests
  nginx:
    image: triplebits/nginx:latest
    tty: true
    depends_on:
      - database
      - php-fpm
    volumes:
      - ./var/www:/var/www
      - ./docker/nginx/sites-enabled/.:/etc/nginx/sites-enabled
      - ./src/.:/var/www/single/wp-content/plugins/wp-staging-pro
      - ./src/.:/var/www/single_tests/wp-content/plugins/wp-staging-pro
      - ./src/.:/var/www/multi/wp-content/plugins/wp-staging-pro
      - ./src/.:/var/www/multi_tests/wp-content/plugins/wp-staging-pro
    ports:
      - ${DOCKER_GATEWAY_IP}:80:80
      - ${DOCKER_GATEWAY_IP}:443:443
