<?php

// scoper-autoload.php @generated by PhpScoper

$loader = require_once __DIR__.'/autoload.php';

// Functions whitelisting. For more information see:
// https://github.com/humbug/php-scoper/blob/master/README.md#functions-whitelisting
if (!function_exists('di52_callbackClosure')) {
    function di52_callbackClosure() {
        return \WPStaging\Vendor\di52_callbackClosure(...func_get_args());
    }
}
if (!function_exists('di52_instanceClosure')) {
    function di52_instanceClosure() {
        return \WPStaging\Vendor\di52_instanceClosure(...func_get_args());
    }
}
if (!function_exists('composerRequirewpstgfree')) {
    function composerRequirewpstgfree() {
        return \WPStaging\Vendor\composerRequirewpstgfree(...func_get_args());
    }
}

return $loader;
