<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'WPStaging\\Vendor\\xrstf\\Composer52\\' => array($vendorDir . '/xrstf/composer-php52/lib/xrstf/Composer52'),
    'WPStaging\\Vendor\\Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'WPStaging\\Vendor\\Symfony\\Component\\Finder\\' => array($vendorDir . '/symfony/finder'),
    'WPStaging\\Vendor\\Symfony\\Component\\Filesystem\\' => array($vendorDir . '/symfony/filesystem'),
    'WPStaging\\Vendor\\Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'WPStaging\\' => array($baseDir . '/'),
);
