name: PHPUnit

on: [push]

jobs:
  build:

    timeout-minutes: 5

    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        working-directory: ./src
        run: composer validate

      - name: Install dependencies
        working-directory: ./src
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Start MySQL service
        run: |
          sudo /etc/init.d/mysql start

      - name: Verify Database Connection
        run: |
          while ! mysqladmin ping --silent; do
            sleep 1
          done

      # TODO RPoC
      - name: Install Test Database
        run: |
          mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS test;"
          mysql -u root -proot test < ./tests/unit/Command/Database/Export/database-sample.sql

      - name: Download & Extract WP
        run: |
          wget http://wordpress.org/latest.tar.gz
          tar xfz latest.tar.gz

      - name: Run unit tests
        env:
          DB_HOST: localhost
          DB_USER: root
          DB_PASSWORD: root
          WP_ROOT: ./wordpress/
        run: php src/vendor/bin/phpunit -c ./
