name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      working-directory: ./src
      run: composer install --no-dev

    - uses: actions/checkout@master
    - name: Build
      run: |
        npm install
        grunt build

    - name: WordPress Plugin Deploy
      uses: WP-Staging/action-wordpress-plugin-deploy@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: wp-staging
